### PR TITLE
Resolves #4. 

### LINKED ISSUE #4: Ambigous slug
If you contain a model which also has a slug, you'll get an SQL error for an ambiguous field, but if you add the table class you get an InvalidArgumentException because the 'slug' key isn't defined.

```php
        $post = $this->Posts->find('slugged', ['Posts.slug' => $slug])
            ->contain([
                'PostCategories',
                'Users'
            ])
            ->where([
                'Posts.status_id' => 1
            ])
            ->first();
```

### PR DESCRIPTION
**Pull request by davidyell**
Add the table class alias to the field to prevent ambiguous field when containing tables which also have a slug field.

### CODE REVIEW

File: src/Model/Behavior/SlugBehavior.php [hunk 1]
```diff
@@ -182,7 +182,7 @@ public function findSlugged(Query $query, array $options)
             throw new InvalidArgumentException('The `slug` key is required by the `slugged` finder.');
         }
 
-        return $query->where([$this->config('field') => $options['slug']]);
+        return $query->where([$this->_table->alias() . '.' . $this->config('field') => $options['slug']]);
```
Comment (ADmad) [inline src/Model/Behavior/SlugBehavior.php]: Use `Table::aliasField()` instead of string concatenation.

**Comment by ADmad** [comment]
Test needed to avoid regression.

**Comment by davidyell** [comment]
Some explanation would be appreciated, otherwise I learn nothing and am
just pressing buttons to appease you, which puts me off wanting to submit
PRs.

**Comment by ADmad** [comment]
Explanation for what?

**Comment by davidyell** [comment]
Why is string concatenation bad?
